INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/ipinfo.png', 'IPinfo.io ', 3.0,'Data contains a list which returns the number of times our webiste is visited per day.',0,500,'',0,1);

INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/bigdatacloud.png','BigDataCloud''s IP Address Geolocation API for Cybersecurity Systems and Professionals', 4.0,'Number of reported cyber attacks per day.',0,200,'',0,1);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/gaialens.jpeg', 'GaiaLens News Data', 2.0,'Number of tweets per minute.',0,800,'DP',0,1);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/customweather.png', 'CustomWeather - Historical Hourly and Daily Weather Observations - 100 Years', 1.0,'Number of lightning strikes per hour.',0,1500,'',0,2);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/shipsdna.jpeg', 'Marine Vessels & Ships - Engine Manufacturer Data', 3,'Number of ships entering US waters per hour.',0,450,'',0,2);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/customweather.png', 'CustomWeather - Historical Hourly Wind and Air Density Data at 100 meters - 40 Years', 0.5,'Number of wind direction changes per hour.',0,700,'',0,2);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/safegraph.jpg', 'Location Data | Global Store Data', 4,'Walmart purchases per minute',0,980,'',0,3);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/teragence.png', 'Mobile Cell Tower Coverage', 2.0,'Phone calls made per minute in Ireland.',0,1600,'',0,3);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/safegraph.jpg', 'Location Data', 1.5,'Number of puchases in starbucks per minute',0,150,'',0,3);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/mapping-resources.jpeg', 'Housing Data', 1.0,'Rent payments made per minute.',0,780,'',0,3);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/safegraph.jpg', 'Alternative Data | US and Canada Transaction Data', 4,'Dollars spent in Montreal per second.',0,600,'',0,4);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/centralamericadata.jpeg', 'Vehicle tracking Data', 4.5,'Motorcycle Crashes per day.',0,1300,'',0,4);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/blue-mail-media.png', 'Aviation Data', 7,'The number of air plane take offs per second.',0,1150,'',0,4);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/big-data-exchange.png', 'BDEX In-Market Automotive Consumers Data', 3,'Vehicle change of ownerships per day in LA.',0,670,'',0,5);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/exchange-data-international.png', 'EDI Security data', 0.5,'Number of alarms set off in London per minute.',0,300,'',0,5);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/televisory.png', 'Televisory Investment Data- Global Coverage of 300,000+ Bonds', 0.6,'Number of cryptocurrency trades made per second.',0,660,'',0,5);
INSERT INTO dataset (image, title, data_point_price, description,visibility,num_data_points,data_points,data_items_sold,category) VALUES ('assets/img/companies/minecraft.png', 'Minecraft Parkour server Data - No.1 Minecraft Parkour data - EU, US, CANADA', 0.7,'Number of server connects per day.',0,440,'',0,6);

INSERT INTO users (name, password, email, role) values ('test','password','test@test.com',1);
